CREATE TABLE CRE_MODALIDAD_PRESTAMO
(
	COD_TIPO NUMBER(3) NOT NULL,
	DESCRIPCION_MOD VARCHAR2(60) NOT NULL,
	TASA_INTERES_ANUAL NUMBER(3,1) NOT NULL,
	RELACION_APORTES NUMBER(2) NOT NULL,
	PLAZO_MAXIMO NUMBER(3) NOT NULL,
	TIPO_GARANTIA VARCHAR2(2) NOT NULL,
	CONSTRAINT PK_ID_MODALIDAD PRIMARY KEY (COD_TIPO)
);


CREATE TABLE SOL_EVENTOS
(
	COD_EVENTO NUMBER(2) NOT NULL,
	NOMBRE_EVENTO VARCHAR2(40) NOT NULL,
	MONTO_COBERTURA NUMBER(10) NOT NULL,
	CANT_MAX_DIAS NUMBER(4) NOT NULL,
	CONSTRAINT PK_ID_EVENTO PRIMARY KEY (COD_EVENTO)
);


CREATE TABLE SOC_MOTIVOS
(
	ID_MOTIVO NUMBER(5) NOT NULL,
	DESCRIPCION VARCHAR2(30) NOT NULL,
	CONSTRAINT PK_ID_MOTIVO PRIMARY KEY (ID_MOTIVO)
);


CREATE TABLE ALD_CONCEPTOS
(
	ID_CONCEPTO NUMBER(3) NOT NULL,
	NOMBRE_CONCEPTO VARCHAR2(40) NOT NULL,
	INGRESO_GASTO VARCHAR2(1) NOT NULL,
	CONSTRAINT PK_ID_CONCEPTO PRIMARY KEY (ID_CONCEPTO)
);


CREATE TABLE AHO_TIPO_MOVIMIENTO
(
	ID_TIPO NUMBER(3) NOT NULL,
	NOMBRE_TIPO VARCHAR2(20) NOT NULL,
	DEBITO_CREDITO VARCHAR2(1) NOT NULL,
	CONSTRAINT PK_ID_TIPO_MOV PRIMARY KEY (ID_TIPO)
);


CREATE TABLE GEN_PARAMETROS
(
	APORTE_MENSUAL NUMBER(8) NOT NULL,
	SOLIDARIDAD_MENSUAL NUMBER(8) NOT NULL,
	ANTIGUEDAD_MINIMA NUMBER(2),
	RUC_COOPERATIVA VARCHAR2(15) NOT NULL,
	INTERES_MORATORIO_BCP NUMBER(3,1) NOT NULL,
	PORC_SEG_VIDA NUMBER(3,2) NOT NULL,
	DIAS_GRACIA NUMBER(2) NOT NULL,
	DIAS_EXON_INT NUMBER(2) NOT NULL
);


CREATE TABLE SOC_SOCIO
(
	ID_SOCIO NUMBER(12) NOT NULL,
	CEDULA VARCHAR2(12) NOT NULL,
	RUC VARCHAR2(12),
	NOMBRE VARCHAR2(50) NOT NULL,
	APELLIDO VARCHAR2(50) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	FECHA_INGRESO DATE NOT NULL,
	DIRECCION VARCHAR2(100) NOT NULL,
	TELEFONO VARCHAR2(20) NOT NULL,
	EMAIL VARCHAR2(50) NOT NULL,
	SUSCRIPTO_NOVEDADES VARCHAR2(1) NOT NULL,
	FIRMA BLOB,
	ESTADO VARCHAR2(1) NOT NULL,
	FECHA_FALLECIMIENTO DATE,
	FECHA_BAJA DATE,
	CONSTRAINT PK_ID_SOCIO PRIMARY KEY (ID_SOCIO)
);


CREATE TABLE CRE_SOLICITUD_PRESTAMOS
(
	ID_SOL_CRED NUMBER(12) NOT NULL,
	FECHA_PRESENTACION DATE NOT NULL,
	SITUACION VARCHAR2(1) NOT NULL,
	MONTO_SOLICITADO NUMBER(12) NOT NULL,
	MONTO_CONCEDIDO NUMBER(12) NOT NULL,
	PLAZO NUMBER(3) NOT NULL,
	TASA_INTERES NUMBER(3,1) NOT NULL,
	OBSERVACION VARCHAR2(300),
	SOCIO_DEUDOR NUMBER(12) NOT NULL,
	SOCIO_CODEUDOR NUMBER(12),
	COD_TIPO NUMBER(3) NOT NULL,
	CONSTRAINT PK_ID_SOL_PRES PRIMARY KEY (ID_SOL_CRED)
);


CREATE TABLE CRE_PRESTAMOS
(
	NRO_PRESTAMO NUMBER(12) NOT NULL,
	FECHA_GENERACION DATE NOT NULL,
	FECHA_DESEMBOLSO DATE NOT NULL,
	FECHA_CANCELACION DATE,
	CAPITAL_A_PAGAR NUMBER(12) NOT NULL,
	INT_A_PAGAR NUMBER(12) NOT NULL,
	CAPITAL_PAGADO NUMBER(12) NOT NULL,
	INT_PAGADO NUMBER(12) NOT NULL,
	ESTADO VARCHAR2(1) NOT NULL,
	ID_SOL_CRED NUMBER(12) NOT NULL,
	CONSTRAINT PK_ID_PRESTAMO PRIMARY KEY (NRO_PRESTAMO)
);


CREATE TABLE CRE_CUOTAS
(
	NRO_PRESTAMO NUMBER(12) NOT NULL,
	NRO_CUOTA NUMBER(3) NOT NULL,
	SALDO_CAPITAL NUMBER(12) NOT NULL,
	AMORTIZACION NUMBER(12) NOT NULL,
	INTERES NUMBER(12) NOT NULL,
	SEGURO_VIDA NUMBER(8) NOT NULL,
	MONTO_CUOTA NUMBER(16) NOT NULL,
	FECHA_VENCIMIENTO DATE NOT NULL,
	CONSTRAINT PK_ID_CUO_PRES PRIMARY KEY (NRO_PRESTAMO, NRO_CUOTA)
);


CREATE TABLE CRE_PAGOS
(
	ID_PAGO NUMBER(12) NOT NULL,
	FECHA_PAGO DATE NOT NULL,
	CAPITAL_PAGADO NUMBER(12) NOT NULL,
	INT_PAGADO NUMBER(12) NOT NULL,
	INT_MORA_PAGADO NUMBER(10) NOT NULL,
	SEG_VIDA_PAGADO NUMBER(8) NOT NULL,
	TOTAL_PAGADO NUMBER(16) NOT NULL,
	NRO_PRESTAMO NUMBER(12) NOT NULL,
	NRO_CUOTA NUMBER(3) NOT NULL,
	CONSTRAINT PK_ID_PAGO PRIMARY KEY (ID_PAGO)
);


CREATE TABLE SOL_SOLICITUD_PREMIOS
(
	ID NUMBER(10) NOT NULL,
	FECHA_PRESENTACION DATE NOT NULL,
	FECHA_DESDE DATE NOT NULL,
	FECHA_HASTA DATE NOT NULL,
	CONCEDIDO VARCHAR2(1) NOT NULL,
	COD_EVENTO NUMBER(2) NOT NULL,
	ID_SOCIO NUMBER(12) NOT NULL,
	CONSTRAINT PK_ID_SOL_PREM PRIMARY KEY (ID)
);


CREATE TABLE SOC_SOLICITUD_RENUNCIA
(
	ID_SOL_REN NUMBER(10) NOT NULL,
	FECHA_PRESENTACION DATE NOT NULL,
	APROBADA VARCHAR2(1) NOT NULL,
	OBSERVACIONES VARCHAR2(300),
	ID_MOTIVO NUMBER(5) NOT NULL,
	ID_SOCIO NUMBER(12) NOT NULL,
	CONSTRAINT PK_ID_SOL_REN PRIMARY KEY (ID_SOL_REN)
);


CREATE TABLE SOC_LIQUIDACION_RENUNCIA
(
	ID_LIQUIDACION NUMBER(10) NOT NULL,
	MONTO_DEBITOS NUMBER(15) NOT NULL,
	MONTO_CREDITOS NUMBER(15) NOT NULL,
	SALDO_A_FAVOR NUMBER(15) NOT NULL,
	NRO_PAGARE NUMBER(8) NOT NULL,
	ID_SOL_REN NUMBER(10) NOT NULL,
	CONSTRAINT PK_ID_LIQUID PRIMARY KEY (ID_LIQUIDACION)
);


CREATE TABLE ALD_INMUEBLES
(
	ID_INMUEBLE NUMBER(8) NOT NULL,
	ID_SOCIO NUMBER(12) NOT NULL,
	CTA_CTE_CATASTRAL VARCHAR2(20) NOT NULL,
	FINCA VARCHAR2(15) NOT NULL,
	SUPERFICIE_M2 NUMBER(4) NOT NULL,
	VALOR_FISCAL NUMBER(15) NOT NULL,
	VALOR_AVALUO NUMBER(15) NOT NULL,
	CONSTRAINT PK_ID_INMUEBLE PRIMARY KEY (ID_INMUEBLE)
);


CREATE TABLE ALD_RODADOS
(
	RUA VARCHAR2(30) NOT NULL,
	ID_SOCIO NUMBER(12) NOT NULL,
	TIPO_VEHICULO VARCHAR2(20) NOT NULL,
	MARCA VARCHAR2(25) NOT NULL,
	MODELO VARCHAR2(25) NOT NULL,
	VALOR NUMBER(12) NOT NULL,
	FECHA_ADQUISICION DATE NOT NULL,
	CONSTRAINT PK_ID_RODADOS PRIMARY KEY (RUA)
);


CREATE TABLE ALD_DECLARACION_JURADA
(
	ID_DECLARACION NUMBER(10) NOT NULL,
	FECHA_PRESENTACION DATE NOT NULL,
	OCUPACION VARCHAR2(30) NOT NULL,
	EMPRESA_ACTUAL VARCHAR2(30),
	MOTIVO_PRESENTACION VARCHAR2(100) NOT NULL,
	OBSERVACIONES VARCHAR2(300),
	ID_SOCIO NUMBER(12) NOT NULL,
	CONSTRAINT PK_ID_DECLARACION PRIMARY KEY (ID_DECLARACION)
);


CREATE TABLE ALD_DETALLE_DECLARACION
(
	ID_DECLARACION NUMBER(10) NOT NULL,
	NRO_ITEM NUMBER(5) NOT NULL,
	IMPORTE NUMBER(15) NOT NULL,
	ID_CONCEPTO NUMBER(3) NOT NULL,
	CONSTRAINT PK_ID_DET_DECLAR PRIMARY KEY (ID_DECLARACION, NRO_ITEM)
);


CREATE TABLE AHO_CUENTA_AHORRO
(
	ID_CUENTA NUMBER(8) NOT NULL,
	ID_SOCIO NUMBER(12) NOT NULL,
	ESTADO VARCHAR2(1) NOT NULL,
	TASA_INTERES NUMBER(3,1) NOT NULL,
	FECHA_APERTURA DATE NOT NULL,
	FECHA_CANCEL DATE,
	SALDO_BLOQUEADO NUMBER(12) NOT NULL,
	SALDO_DISPONIBLE NUMBER(12) NOT NULL,
	CONSTRAINT PK_ID_AHORRO PRIMARY KEY (ID_CUENTA)
);


CREATE TABLE AHO_MOVIMIENTOS_CUENTA
(
	ID_MOVIMIENTO NUMBER(12) NOT NULL,
	FECHA_MOVIMIENTO DATE NOT NULL,
	IMPORTE NUMBER(15) NOT NULL,
	ID_TIPO NUMBER(3) NOT NULL,
	ID_CUENTA NUMBER(8) NOT NULL,
	CONSTRAINT PK_ID_MOV PRIMARY KEY (ID_MOVIMIENTO)
);


CREATE TABLE SOC_OBLIGACIONES
(
	ID_OBLIGACION NUMBER(10) NOT NULL,
	ANHO NUMBER(4) NOT NULL,
	TOTAL_A_ABONAR NUMBER(8) NOT NULL,
	SALDO NUMBER(8) NOT NULL,
	TIPO_OBLIGACION VARCHAR2(1) NOT NULL,
	ID_SOCIO NUMBER(12) NOT NULL,
	CONSTRAINT PK_COD_OBLIG PRIMARY KEY (ID_OBLIGACION)
);


CREATE TABLE SOC_DETALLE_OBLIGACIONES
(
	ID_OBLIGACION NUMBER(10) NOT NULL,
	NUM_CUOTA NUMBER(2) NOT NULL,
	MONTO NUMBER(8) NOT NULL,
	FECHA_PAGO DATE,
	CONSTRAINT PK_DET_OBLIG PRIMARY KEY (ID_OBLIGACION, NUM_CUOTA)
);


ALTER TABLE CRE_SOLICITUD_PRESTAMOS ADD CONSTRAINT MODALIDAD_PRESTAMO_SOLICITU
FOREIGN KEY (COD_TIPO)
REFERENCES CRE_MODALIDAD_PRESTAMO (COD_TIPO);

ALTER TABLE SOL_SOLICITUD_PREMIOS ADD CONSTRAINT EVENTOS_SOLICITUD_PREMIOS_FK
FOREIGN KEY (COD_EVENTO)
REFERENCES SOL_EVENTOS (COD_EVENTO);

ALTER TABLE SOC_SOLICITUD_RENUNCIA ADD CONSTRAINT MOTIVOS_SOLICITUD_RENUNCIA_FK
FOREIGN KEY (ID_MOTIVO)
REFERENCES SOC_MOTIVOS (ID_MOTIVO);

ALTER TABLE ALD_DETALLE_DECLARACION ADD CONSTRAINT CONCEPTOS_DETALLE_DECLARACI
FOREIGN KEY (ID_CONCEPTO)
REFERENCES ALD_CONCEPTOS (ID_CONCEPTO);

ALTER TABLE AHO_MOVIMIENTOS_CUENTA ADD CONSTRAINT TIPO_MOVIMIENTO_MOVIMIENTOS
FOREIGN KEY (ID_TIPO)
REFERENCES AHO_TIPO_MOVIMIENTO (ID_TIPO);

ALTER TABLE SOC_OBLIGACIONES ADD CONSTRAINT SOCIO_OBLIGACIONES_FK
FOREIGN KEY (ID_SOCIO)
REFERENCES SOC_SOCIO (ID_SOCIO);

ALTER TABLE AHO_CUENTA_AHORRO ADD CONSTRAINT SOCIO_CUENTA_AHORRO_FK
FOREIGN KEY (ID_SOCIO)
REFERENCES SOC_SOCIO (ID_SOCIO);

ALTER TABLE ALD_DECLARACION_JURADA ADD CONSTRAINT SOCIO_DECLARACION_JURADA_FK
FOREIGN KEY (ID_SOCIO)
REFERENCES SOC_SOCIO (ID_SOCIO);

ALTER TABLE ALD_RODADOS ADD CONSTRAINT SOCIO_RODADOS_FK
FOREIGN KEY (ID_SOCIO)
REFERENCES SOC_SOCIO (ID_SOCIO);

ALTER TABLE ALD_INMUEBLES ADD CONSTRAINT SOCIO_INMUEBLES_FK
FOREIGN KEY (ID_SOCIO)
REFERENCES SOC_SOCIO (ID_SOCIO);

ALTER TABLE SOC_SOLICITUD_RENUNCIA ADD CONSTRAINT SOCIO_SOLICITUD_RENUNCIA_FK
FOREIGN KEY (ID_SOCIO)
REFERENCES SOC_SOCIO (ID_SOCIO);

ALTER TABLE SOL_SOLICITUD_PREMIOS ADD CONSTRAINT SOCIO_SOLICITUD_PREMIOS_FK
FOREIGN KEY (ID_SOCIO)
REFERENCES SOC_SOCIO (ID_SOCIO);

ALTER TABLE CRE_SOLICITUD_PRESTAMOS ADD CONSTRAINT SOCIO_SOLICITUD_PRESTAMOS_FK
FOREIGN KEY (SOCIO_DEUDOR)
REFERENCES SOC_SOCIO (ID_SOCIO);

ALTER TABLE CRE_SOLICITUD_PRESTAMOS ADD CONSTRAINT SOCIO_SOLICITUD_PRESTAMOS_FK1
FOREIGN KEY (SOCIO_CODEUDOR)
REFERENCES SOC_SOCIO (ID_SOCIO);

ALTER TABLE CRE_PRESTAMOS ADD CONSTRAINT SOLICITUD_PRESTAMOS_PRESTAMO
FOREIGN KEY (ID_SOL_CRED)
REFERENCES CRE_SOLICITUD_PRESTAMOS (ID_SOL_CRED);

ALTER TABLE CRE_CUOTAS ADD CONSTRAINT PRESTAMOS_CUOTAS_FK
FOREIGN KEY (NRO_PRESTAMO)
REFERENCES CRE_PRESTAMOS (NRO_PRESTAMO);

ALTER TABLE CRE_PAGOS ADD CONSTRAINT CRE_CUOTAS_CRE_PAGOS_FK
FOREIGN KEY (NRO_PRESTAMO, NRO_CUOTA)
REFERENCES CRE_CUOTAS (NRO_PRESTAMO, NRO_CUOTA);

ALTER TABLE SOC_LIQUIDACION_RENUNCIA ADD CONSTRAINT SOLICITUD_RENUNCIA_LIQUIDAC
FOREIGN KEY (ID_SOL_REN)
REFERENCES SOC_SOLICITUD_RENUNCIA (ID_SOL_REN);

ALTER TABLE ALD_DETALLE_DECLARACION ADD CONSTRAINT DECLARACION_JURADA_DETALLE
FOREIGN KEY (ID_DECLARACION)
REFERENCES ALD_DECLARACION_JURADA (ID_DECLARACION);

ALTER TABLE AHO_MOVIMIENTOS_CUENTA ADD CONSTRAINT CUENTA_AHORRO_MOVIMIENTOS
FOREIGN KEY (ID_CUENTA)
REFERENCES AHO_CUENTA_AHORRO (ID_CUENTA);

ALTER TABLE SOC_DETALLE_OBLIGACIONES ADD CONSTRAINT OBLIGACIONES_DETALLE_OBLIGA
FOREIGN KEY (ID_OBLIGACION)
REFERENCES SOC_OBLIGACIONES (ID_OBLIGACION);

CREATE SEQUENCE SEQ_PRESTAMO
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_PAG_CUO
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE SEQUENCE SEQ_NRO_PAGARE
MINVALUE 1
MAXVALUE 99999999
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;